resolver: lts-12.8

# Older packages that we'd still like to test, but haven't made it
# into the latest LTS.
extra-deps:
# Uses c2hs:
- hsndfile-0.8.0
# Has old `Cabal-version` and an executable with no explicit build-depends:
- hsx2hs-0.14.1.3
- hashable-time-0.2.0.1
